source/accounts/urls.py
from django.urls import path

from accounts.views import login_view, logout_view, register_view, UserDetailView, UserUpdateView, \
    UserUpdatePasswordView, validate_username

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', register_view, name='registration'),
    path('ajax/validate_username/', validate_username, name='validate_username'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('profile/update_password/<int:pk>/', UserUpdatePasswordView.as_view(), name='user_change_password')
]

app_name = 'accounts'

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models

# Create your models here.

source/accounts/forms.py
from django.contrib.auth.models import User
from django import forms


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label='Password', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Confirm password',  widget=forms.PasswordInput, strip=False)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords does not match!")
        return password_confirm

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'password_confirm']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Name:', 'last_name': 'Last Name:', 'email': 'Email:'}


class UserPasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label='Password', strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Password confirm', strip=False, widget=forms.PasswordInput)
    old_password = forms.CharField(label='Old password', strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Password does not match')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')

        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Old password does not match')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data['password'])

        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView

from accounts.forms import UserCreationForm, UserChangeForm, UserPasswordChangeForm


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        next_url = request.POST.get('next')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            if next_url:
                return redirect(next_url)
            return redirect('webapp:home')
        else:
            context['has_error'] = True
            context['next'] = next_url
            context['username'] = username
    else:
        context = {'next': request.GET.get('next')}
    return render(request, 'registration/login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:home')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('webapp:home')
    else:
        form = UserCreationForm()
    return render(request, 'user_create.html', context={'form': form})


def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username__iexact=username).exists()
    }
    return JsonResponse(data)


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserUpdateView(UpdateView):
    model = User
    template_name = 'user_update.html'
    form_class = UserChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserUpdatePasswordView(UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = UserPasswordChangeForm
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('accounts:login')

source/accounts/templates/user_create.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Registration | Tanze.com</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/registration.css' %}">
  </head>
  <body>

  <div class="container">
      <form action="{% url 'accounts:registration' %}" method="POST">
          {% csrf_token %}

          {% for error in form.non_field_errors %}
              <p class="form-error">{{ error }}</p>
          {% endfor %}
          <h1>Register</h1>
          <p>Please fill in this form to create an account.</p><hr>
          {% for field in form %}
              <label for="{{ field.id_for_label }}" class="form-label {% if field.field.required %}required{% endif %}">{{ field.label }}</label>
              {% if field.errors %}
                  {{ field }}
                  {% for error in field.errors %}
                      <p class="form-error">{{ error }}</p>
                  {% endfor %}
              {% else %}
                  {{ field }}
              {% endif %}
          {% endfor %}
          <button type="submit" class="registerbtn">Register</button>
      </form>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
{#   <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>#}
    <script src={% static 'js/jquery.min.js' %}></script>
    <script src={% static 'js/main.js' %}></script>
{#    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>#}
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %} {{ user_obj.username }} Detail| Tanze.com{% endblock %}

{% block menu %}
    <li><a class="nav-link" href="{% url 'accounts:user_update' user_obj.pk %}" tabindex="-1" aria-disabled="true">Update info</a></li>
    <li><a class="nav-link" href="{% url 'accounts:user_change_password' user_obj.pk %}" tabindex="-1" aria-disabled="true">Change password</a></li>
{% endblock %}
{% block content %}
    <div class="container">
        <h1>Personal page</h1>
        <p>Имя пользователя: {{ user_obj.username }}</p>
        <p>Имя: {{ user_obj.first_name }}</p>
        <p>Фамилия: {{ user_obj.last_name }}</p>
        <p>Почта: {{ user_obj.email }}</p>
    </div>
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %} Change password | Tanze.com {% endblock %}

{% block menu %}
    <li><a class="nav-link" href="{% url 'accounts:user_update' user_obj.pk %}" tabindex="-1" aria-disabled="true">Update info</a></li>
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Change password</h1>

        <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
            {% include 'partial/form.html' %}
            <input type="submit" value="Update password" class="btn btn-primary">
            <a class="btn btn-secondary" href="{% url 'accounts:user_detail' user_obj.pk %}">Cancel</a>
        </form>
    </div>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}Personal Page| Tanze.com{% endblock %}

{% block menu_links %}
    <li><a class="nav-link" href="{% url "accounts:user_update" user_obj.pk %}" tabindex="-1" aria-disabled="true">Back</a></li>
    <li><a class="nav-link" href="{% url 'accounts:user_change_password' user_obj.pk %}" tabindex="-1" aria-disabled="true">Change password</a></li>
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Personal page</h1>

        <form action="{% url "accounts:user_update" user_obj.pk %}" method="post">
            {% include 'partial/form.html' %}
            <input type="submit" value="Update info" class="btn btn-primary">
            <a class="btn btn-secondary" href="{% url 'accounts:user_detail' user_obj.pk %}">Cancel</a>
        </form>
    </div>
{% endblock %}