source/accounts/urls.py
from django.urls import path

from accounts.views import login_view, logout_view, register_view, UserDetailView, UserUpdateView, \
    UserUpdatePasswordView, validate_username

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registration/', register_view, name='registration'),
    path('ajax/validate_username/', validate_username, name='validate_username'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('profile/update_password/<int:pk>/', UserUpdatePasswordView.as_view(), name='user_change_password')
]

app_name = 'accounts'

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import ProductViewList, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    SearchResults, ProductCategoryView, about_us, contact_us

urlpatterns = [
    path('', ProductViewList.as_view(), name='home'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/search/', SearchResults.as_view(), name='product_search'),
    path('product/', ProductCategoryView.as_view(), name='product_category'),

    path('about_us/', about_us, name='about_us'),
    path('contact_us/', contact_us, name='contact_us'),
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models

CATEGORY_CHOICES = (
    ('other_category', 'Other'),
    ('cloth_category', 'Clothes'),
    ('food_category', 'Food'),
    ('household_category', 'Household items'),
    ('electronic', 'Computers'),
)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Product name:')
    description = models.CharField(max_length=2000, null=True, blank=True, verbose_name='Product description:')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES,
                                default=CATEGORY_CHOICES[0][0], verbose_name='Category:')
    left = models.PositiveIntegerField(verbose_name='How much left..')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Product price:')
    image = models.ImageField(upload_to='product_images', null=False, blank=False, verbose_name='Product image:')
    author = models.ForeignKey('auth.User', related_name='product',
                               on_delete=models.CASCADE, null=True, blank=True, verbose_name='Author')

    class Meta:
        ordering = ('category', 'name',)

    def __str__(self):
        return self.name

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'left', 'price', 'image']

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) <= 10:
            raise ValidationError("This field should be more than 10 symbols.", code='too_short')
        return name


class Subscribe(forms.Form):
    email = forms.EmailField()

    def __str__(self):
        return self.email

source/webapp/views/footer_view.py
from django.core.mail import send_mail
from django.shortcuts import render

from main.settings import EMAIL_HOST_USER
from webapp import forms


def about_us(request):
    return render(request, 'about_us/about_us.html')


def contact_us(request):
    sub = forms.Subscribe()
    if request.method == 'POST':
        sub = forms.Subscribe(request.POST)
        subject = 'Thank you for getting in touch!'
        message = 'We appreciate you contacting us Tanze. One of our colleagues will get back in touch with you soon!'
        recepient = str(sub['email'].value())
        send_mail(subject,
                  message, EMAIL_HOST_USER, [recepient], fail_silently=False)
        return render(request, 'contact_us/contact_us.html', {'recepient': recepient})
    return render(request, 'contact_us/index.html', {'form': sub})

source/webapp/views/product_view.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product


class ProductViewList(ListView):
    model = Product
    template_name = 'product/product_index.html'
    context_object_name = 'products'
    paginate_by = 6
    paginate_orphans = 1

    def get_queryset(self):
        product = Product.objects.exclude(left=0)
        return product


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/product_detail.html'
    context_object_name = 'product'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    template_name = 'product/product_create.html'
    form_class = ProductForm
    permission_required = 'webapp.add_product'
    permission_denied_message = 'Accces denided.'

    def form_valid(self, form):
        if str(self.request.user) != 'AnonymousUser':
            form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    template_name = 'product/product_update.html'
    fields = ('name', 'description', 'category', 'left', 'price', 'image')
    context_object_name = 'product'

    def test_func(self):
        if self.request.user.has_perm('change_product') or self.get_object().author == self.request.user:
            return True

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'product/product_delete.html'
    context_object_name = 'product'
    success_url = reverse_lazy('webapp:home')

    def test_func(self):
        if self.request.user.has_perm('delete_product') or self.get_object().author == self.request.user:
            return True

    def delete(self, request, *args, **kwargs):
        product = self.object = self.get_object()
        product.delete()
        return HttpResponseRedirect(self.get_success_url())


class ProductCategoryView(ListView):
    model = Product
    template_name = 'product/product_category.html'
    context_object_name = 'products'
    paginate_by = 6
    paginate_orphans = 1
    page_kwarg = 'category'

    def get_queryset(self):
        query = self.request.GET.get('list')
        product = Product.objects.all().filter(category__contains=query)
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('list')
        return context


class SearchResults(ListView):
    model = Product
    template_name = 'product/search_results.html'
    ordering = ('name',)
    paginate_by = 6
    paginate_orphans = 1
    page_kwarg = 'product'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query == "":
            messages.add_message(self.request, messages.WARNING, 'Please, fill out the search bar.')
        object_list = Product.objects.filter(
            Q(name__icontains=query)
        )
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        paginator = Paginator(products, 6)
        page = self.request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context['products'] = products
        context['query'] = self.request.GET.get('q')
        return context

source/webapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="https://cdn2.iconfinder.com/data/icons/business-808/34/32-512.png"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'webapp:home'%}">Tanze</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'webapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          {% if perms.webapp.add_product %}
            <a class="nav-link" href="{% url 'webapp:product_create' %}">Add product</a>
          {% endif %}
      </li>
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li>#}
      <li class="nav-item">
          {% if request.user.is_authenticated %}
              <li><a class="nav-link" href="{% url 'accounts:logout' %}" tabindex="-1" aria-disabled="true">Logout</a></li>
              <li><a class="nav-link" href="{% url 'accounts:user_detail' user.pk %}" tabindex="-1">Hi,{{ user.username }}!</a></li>
              {% block menu %} {% endblock %}
          {% else %}
              <li><a class="nav-link" href="{% url 'accounts:registration' %}" aria-disabled="true">Sign Up</a></li>
              <li><a class="nav-link" href="{% url 'accounts:login' %}" aria-disabled="true">Login</a></li>
          {% endif %}
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'webapp:product_search' %}" method="get">
      <input class="form-control mr-sm-2" type="search" placeholder="I'm shopping for..." aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
  </head>
  <body>

  {% include 'partial/messages.html' %}

  {% block content %} {% endblock %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://kit.fontawesome.com/0d32c2a2d9.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body><br/>

  <!-- Site footer -->

    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">Tanze.com <i>Let us deliver your product
            </i> This website is for everyone that wants to take advantage of doing online shops. Your interest is our job. Let us ship your product right to you.</p>
          </div>
          <div class="col-xs-6 col-md-3">
            <h6>Categories</h6>
                  <ul class="footer-links">
                      <li><a href="{% url 'webapp:product_category' %}?list=cloth_category">Clothes</a></li>
                      <li><a href="{% url 'webapp:product_category' %}?list=Food">Food</a></li>
                      <li><a href="{% url 'webapp:product_category' %}?list=household_category">Household items</a></li>
                      <li><a href="{% url 'webapp:product_category' %}?list=electronic">Computer/Laptop</a></li>
                      <li><a href="{% url 'webapp:product_category' %}?list=other_category">Other</a></li>
                  </ul>
          </div>
          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="{% url 'webapp:about_us' %}">About Us</a></li>
              <li><a href="{% url 'webapp:contact_us' %}">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by
         <a href="{% url 'webapp:home' %}">Tanze.com</a>.
            </p>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fab fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fab fa-twitter-square"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fab fa-linkedin-in"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
</footer>
</html>