source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import ProductViewList, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    SearchResults, ProductCategoryView, about_us, contact_us

urlpatterns = [
    path('', ProductViewList.as_view(), name='home'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/search/', SearchResults.as_view(), name='product_search'),
    path('product/', ProductCategoryView.as_view(), name='product_category'),

    path('about_us/', about_us, name='about_us'),
    path('contact_us/', contact_us, name='contact_us'),
]

app_name = 'webapp'

source/webapp/models.py
from django.db import models

CATEGORY_CHOICES = (
    ('other_category', 'Other'),
    ('cloth_category', 'Clothes'),
    ('food_category', 'Food'),
    ('household_category', 'Household items'),
    ('electronic', 'Computers'),
)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Product name:')
    description = models.CharField(max_length=2000, null=True, blank=True, verbose_name='Product description:')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES,
                                default=CATEGORY_CHOICES[0][0], verbose_name='Category:')
    left = models.PositiveIntegerField(verbose_name='How much left..')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Product price:')
    image = models.ImageField(upload_to='product_images', null=False, blank=False, verbose_name='Product image:')
    author = models.ForeignKey('auth.User', related_name='product',
                               on_delete=models.CASCADE, null=True, blank=True, verbose_name='Author')

    class Meta:
        ordering = ('category', 'name',)

    def __str__(self):
        return self.name

source/webapp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from webapp.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'left', 'price', 'image']

    def clean_name(self):
        name = self.cleaned_data['name']
        if len(name) <= 10:
            raise ValidationError("This field should be more than 10 symbols.", code='too_short')
        return name


class Subscribe(forms.Form):
    email = forms.EmailField()

    def __str__(self):
        return self.email

source/webapp/views/footer_view.py
from django.core.mail import send_mail
from django.shortcuts import render

from main.settings import EMAIL_HOST_USER
from webapp import forms


def about_us(request):
    return render(request, 'about_us/about_us.html')


def contact_us(request):
    sub = forms.Subscribe()
    if request.method == 'POST':
        sub = forms.Subscribe(request.POST)
        subject = 'Thank you for getting in touch!'
        message = 'We appreciate you contacting us Tanze. One of our colleagues will get back in touch with you soon!'
        recepient = str(sub['email'].value())
        send_mail(subject,
                  message, EMAIL_HOST_USER, [recepient], fail_silently=False)
        return render(request, 'contact_us/contact_us.html', {'recepient': recepient})
    return render(request, 'contact_us/index.html', {'form': sub})

source/webapp/views/product_view.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product


class ProductViewList(ListView):
    model = Product
    template_name = 'product/product_index.html'
    context_object_name = 'products'
    paginate_by = 6
    paginate_orphans = 1

    def get_queryset(self):
        product = Product.objects.exclude(left=0)
        return product


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/product_detail.html'
    context_object_name = 'product'


class ProductCreateView(PermissionRequiredMixin, CreateView):
    model = Product
    template_name = 'product/product_create.html'
    form_class = ProductForm
    permission_required = 'webapp.add_product'
    permission_denied_message = 'Accces denided.'

    def form_valid(self, form):
        if str(self.request.user) != 'AnonymousUser':
            form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    template_name = 'product/product_update.html'
    fields = ('name', 'description', 'category', 'left', 'price', 'image')
    context_object_name = 'product'

    def test_func(self):
        if self.request.user.has_perm('change_product') or self.get_object().author == self.request.user:
            return True

    def get_success_url(self):
        return reverse('webapp:product_detail', kwargs={'pk': self.object.pk})


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'product/product_delete.html'
    context_object_name = 'product'
    success_url = reverse_lazy('webapp:home')

    def test_func(self):
        if self.request.user.has_perm('delete_product') or self.get_object().author == self.request.user:
            return True

    def delete(self, request, *args, **kwargs):
        product = self.object = self.get_object()
        product.delete()
        return HttpResponseRedirect(self.get_success_url())


class ProductCategoryView(ListView):
    model = Product
    template_name = 'product/product_category.html'
    context_object_name = 'products'
    paginate_by = 6
    paginate_orphans = 1
    page_kwarg = 'category'

    def get_queryset(self):
        query = self.request.GET.get('list')
        product = Product.objects.all().filter(category__contains=query)
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('list')
        return context


class SearchResults(ListView):
    model = Product
    template_name = 'product/search_results.html'
    ordering = ('name',)
    paginate_by = 6
    paginate_orphans = 1
    page_kwarg = 'product'

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query == "":
            messages.add_message(self.request, messages.WARNING, 'Please, fill out the search bar.')
        object_list = Product.objects.filter(
            Q(name__icontains=query)
        )
        return object_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = Product.objects.all()
        paginator = Paginator(products, 6)
        page = self.request.GET.get('page')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        context['products'] = products
        context['query'] = self.request.GET.get('q')
        return context

source/webapp/templates/product/product_category.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for product in products %}
                <div class="col-md"><br/>
                    <div class="card" style="width: 20rem;">
                        {% if product.image %}
                            <img src="{{ product.image|thumbnail_url:'avatar' }}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'webapp:product_detail' product.pk %}" style="text-decoration: none">{{ product.name }}</a></h5>
                            <p class="card-text">Category:  {{ product.get_category_display }}</p>
                            <button class="btn btn-primary">Price: ${{ product.price }}</button>
                        </div>
                    </div>
                </div>
                {% empty %}
                <div class="container">
                    <div class="jumbotron">
                        <h1 class="display-4">There is no product in this category ...</h1>
                        <p class="lead">However, you see other products by visiting to main page or create product..</p>
                        <hr class="my-4">
                        <a class="btn btn-primary" href="{% url 'webapp:product_create' %}" role="button">Create product</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% if is_paginated %}
        {% include 'partial/pagination_category.html' %}
    {% endif %}
    </div>
{% endblock %}

source/webapp/templates/product/product_create.html
{% extends 'base.html' %}

{% block title %} Add product {% endblock %}
{% block content %}
    <div class="container">
        <h1>Add product</h1>
        <form action="{% url 'webapp:product_create'  %}" method="POST" enctype="multipart/form-data">
            {% include 'partial/form.html' %}
            <input type="submit" value="Add product" class="btn btn-primary">
            <a class="btn btn-secondary" href="{% url 'webapp:home' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

source/webapp/templates/product/product_delete.html
{% extends 'base.html' %}
{% block title %} Delete Article {% endblock %}
{% block content %}
    <div class="container">
        <h1>Are you sure you want to delete "{{ product }}"?</h1>
        <form action="{% url 'webapp:product_delete' product.pk %}" method="post">
            {% csrf_token %}
            <p><input class="btn btn-danger" type="submit" value="Confirm"></p>
            <p><a class="btn btn-secondary" href="{% url 'webapp:product_detail' product.pk %}">Cancel</a></p>
        </form>
    </div>
{% endblock %}

source/webapp/templates/product/product_detail.html
{% extends 'base.html'%}
{% load static %}
{% block title %} {{ product.name }} {% endblock %}

{% block content %}
    <div class="container"><br/>
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="{{ product.image.url }}" class="card-img" alt="{{ product.name }}">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        {% if product.description %}
                            <p class="card-text"><b>Product description:</b> {{ product.description }}</p>
                        {% else %}
                            <p class="card-text"><b>Product description:</b> No description</p>
                        {% endif %}
                        <p class="card-text"><b>Product category:</b> {{ product.get_category_display }}</p>
                        <p class="card-text"><b>How much left..</b> {{ product.left }}</p>
                        <p class="card-text"><b>Product price:</b> ${{ product.price }}</p>
                        {% if request.user == product.author or request.user.is_superuser %}
                            <a class="btn btn-secondary" href="{% url 'webapp:product_update' product.pk %}">Update product</a>
                        {% endif %}
                        {% if request.user == product.author or request.user.is_superuser %}
                            <a class="btn btn-danger" href="{% url 'webapp:product_delete' product.pk %}">Delete product</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

source/webapp/templates/product/product_index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}Products | Tanze.com {% endblock %}

{% block content %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'images_static/first_slide.jpeg' %}" class="d-block w-100" alt="shop">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images_static/second_slide.jpeg' %}" class="d-block w-100" alt="shop">
            </div>
            <div class="carousel-item">
                <img src="{% static 'images_static/photo.jpeg' %}" class="d-block w-100" alt="shop">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="card">
    <div class="container">
        <img src="{% static 'images_static/coming-soon5.png' %}" class="card-img-top" alt="coming_soon">
        <div class="card-body">
            <h5 class="card-title">Please stay tuned</h5>
            <p class="card-text">Stay tuned for some cool products of Tanze shop</p>
        </div>
    </div>

    <p style="text-align: center">Take a look what we offer</p>

    <div class="container">
        <div class="row">
            {% for product in products %}
                <div class="col-md"><br/>
                    <div class="card" style="width: 20rem;">
                        {% if product.image %}
                            <img src="{{ product.image|thumbnail_url:'avatar' }}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'webapp:product_detail' product.pk %}" style="text-decoration: none">{{ product.name }}</a></h5>
                                <p class="card-text">Category:  {{ product.get_category_display }}</p>
                            <button class="btn btn-primary">Price: ${{ product.price }}</button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    </div>
            {% endblock %}
</div>

source/webapp/templates/product/product_update.html
{% extends 'base.html' %}
{% block title %} {{ product.name }} {% endblock %}
{% block content %}
    <div class="container">
        <h1>Update product</h1>
        <form action="{% url  'webapp:product_update' product.pk %}" method="POST" enctype="multipart/form-data">
            {% include 'partial/form.html' %}
            <input type="submit" value="Update product" class="btn btn-primary">
            <a class="btn btn-secondary" href="{% url 'webapp:home' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

source/webapp/templates/product/search_results.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Search result(s) {% endblock %}
{% block content %}
    <div class="container"><br/>
        <h2>Products/items</h2>
        <div class="row">
            {% for prod in object_list %}<br/>
                <div class="col-md"><br/>
                    <div class="card" style="width: 20rem;">
                        <img src="{{ prod.image|thumbnail_url:'avatar' }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{% url 'webapp:product_detail' prod.pk %}" style="text-decoration: none">{{ prod.name }}</a></h5>
                                <p class="card-text">Category:  {{ prod.get_category_display }}</p>
                            <a href="#" class="btn btn-primary">Price: ${{ prod.price }}</a>
                        </div>
                    </div>
                </div>
            {% empty %}<br/>
                <div class="jumbotron jumbotron-fluid">
                    <div class="container">
                        <h1 class="display-4">There is no product in this query... :/</h1>
                    </div>
                </div>
                <h1>Check out other products, too</h1>
                <div class="row">
                    {% for product in products %}
                        <div class="col md-4"><br/>
                            <div class="card" style="width: 20rem;">
                                {% if product.image %}
                                    <img src="{{ product.image|thumbnail_url:'avatar' }}" class="card-img-top" alt="...">
                                {% endif %}
                                <div class="card-body">
                                    <h5 class="card-title"><a href="{% url 'webapp:product_detail' product.pk %}" style="text-decoration: none">{{ product.name }}</a></h5>
                                    <p class="card-text">Category:  {{ product.get_category_display }}</p>
                                    <button class="btn btn-primary">Price: ${{ product.price }}</button>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="container">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-end">
                            <li class="page-item">
                                {% if products.has_previous %}
                                    <a class="page-link" href="?q={% if query %}{{ query }}{% endif %}&page={{ products.previous_page_number }}" tabindex="-1">previous</a>
                                {% endif %}
                            </li>
                            {% for l in products.paginator.page_range %}
                                {% if forloop.counter < 6 %}
                                    <li class="page-item"><a class="page-link" href="?q={% if query %}{{ query }}{% endif %}&page={{ forloop.counter }}">{{forloop.counter}}</a></li>
                                {% endif %}
                            {% endfor %}
                            <li class="page-item">
                                {% if products.has_next %}
                                    <a class="page-link" href="?q={% if query %}{{ query }}{% endif %}&page={{ products.next_page_number }}" tabindex="-1">next</a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                </div>
            {% endfor %}
            {% if is_paginated %}
                {% include 'partial/search_result_pagination.html' %}
            {% endif %}
        </div>
    </div>
{% endblock %}